---

- name: 'Auth to CrowdStrike API (Windows)'
  win_uri:
    url: "{{ api_base_url }}/oauth2/token"
    url_method: POST
    body: "client_id={{ falcon_client_id }}&client_secret={{ falcon_client_secret }}"
    return_content: yes
    status_code: 201
    headers:
      Accept: "application/json"
      Content-Type: "application/x-www-form-urlencoded"
  register: crowdstrike_auth

- name: 'Download CrowdStrike Falcon EXE'
  win_get_url:
    url: "{{ api_base_url }}/sensors/entities/download-installer/v1?id={{ win[0].hash }}"
    url_timeout: 120
    headers:
      Authorization: "Bearer {{ crowdstrike_auth.json.access_token }}"
      Accept: "application/octet-stream"
      Content-Type: "application/json"
    dest: C:\Users\ansible\Downloads\falcon-sensor.exe

- name: 'Install the obtained EXE (windows)'
  win_package:
    path: C:\Users\ansible\Downloads\falcon-sensor.exe
    state: present
    arguments:
      - /install
      - /quiet
      - /norestart
      - "CID={{ crowdstrike_customer_id }}"
...