---

- name: 'Auth to CrowdStrike API (Windows)'
  win_uri:
    url: "{{ api_base_url }}/oauth2/token"
    url_method: POST
    body: "client_id={{ falcon_client_id }}&client_secret={{ falcon_client_secret }}"
    return_content: yes
    status_code: 201
    headers:
      Accept: "application/json"
      Content-Type: "application/x-www-form-urlencoded"
  register: crowdstrike_auth
  when: ansible_facts['os_family'] == 'Windows'

- name: 'Download CrowdStrike Falcon EXE'
  win_get_url:
    url: "{{ api_base_url }}/sensors/entities/download-installer/v1?id={{ item.hash }}"
    url_timeout: 120
    headers:
      Authorization: "Bearer {{ crowdstrike_auth.json.access_token }}"
      Accept: "application/octet-stream"
      Content-Type: "application/json"
    dest: "{{ win_download_path }}"
  when: (ansible_facts['os_family'] == 'Windows' and inventory_hostname is search(item.hostname)) or
    (ansible_distribution is search(item.distribution)
    and
    ansible_distribution_major_version is search(item.major_version)
    and
    ansible_architecture is search(item.architecture))
  loop: "{{ win }}"

- name: 'Install the obtained EXE (windows)'
  win_package:
    path: "{{ win_download_path }}"
    state: present
    arguments:
      - /install
      - /quiet
      - /norestart
      - "CID={{ crowdstrike_customer_id }}"
  when: (ansible_facts['os_family'] == 'Windows' and inventory_hostname is search(item.hostname)) or
    (ansible_distribution is search(item.distribution)
    and
    ansible_distribution_major_version is search(item.major_version)
    and
    ansible_architecture is search(item.architecture))
  loop: "{{ win }}"
...